'use strict'



const pointData = [

    {
    name:"東洋館",
    parking:true,
    babybed:false,
    multisheet:false,
    ostomate:false,
    button:false,
    showertoilet:true,
    lat:38.302116,lon:141.509742,
    popupContent:'<div class="popButton" onClick="setModal("東洋館");"><p>東洋館</p></div>',
    tdTime:"利用可能時間 9:00-16:30　電話 0225−45-2206",
    img:[
    'img/pic/oshika/toyo/toyo1.png',
    'img/pic/oshika/toyo/toyo2.png',
    'img/pic/oshika/toyo/toyo3.png',
    'img/pic/oshika/toyo/toyo4.png',
    'img/pic/oshika/toyo/toyo5.png',],
    },
    // {name:"東洋館",
    // parking:false,
    // babybed:false,
    // multisheet:false,
    // ostomate:false,
    // button:false,
    // showertoilet:true,
    // popupContent:'<div class="popButton" onClick="modal_OshikaToyo()"><p>東洋館</p></div>',
    // lat:38.302116,lon:141.509742,
    // title: '<p><img src="icon/info.png" alt="東洋館です。トイレに近い入り口は、不明です。シャワートイレがあります">東洋館<img onClick="back()"  src="icon/back.png" alt="このボタンで地図に戻ります"></p>',
    // tdTime:"９：００〜１６：３０　45-2206",
    // img:[
    // 'img/pic/oshika/toyo/toyo1.png',
    // 'img/pic/oshika/toyo/toyo2.png',
    // 'img/pic/oshika/toyo/toyo3.png',
    // 'img/pic/oshika/toyo/toyo4.png',
    // 'img/pic/oshika/toyo/toyo5.png',],
    // },
    {name:"牡鹿総合支所",
    parking:false,
    babybed:false,
    multisheet:false,
    ostomate:true,
    button:false,
    showertoilet:true,
    popupContent:'<div class="popButton" onClick="modal_OshikaSogo()"><p>牡鹿総合支所</p></div>',
    lat:38.302183,lon:141.508229,
    title: '<p><img src="icon/info.png" alt="牡鹿総合支所です。トイレに近い入り口は、不明です。オストメイトあります。シャワートイレがあります">牡鹿総合支所<img onClick="back()"  src="icon/back.png" alt="このボタンで地図に戻ります"></p>',
    tdTime:"８：３０〜１７：００（土日祝休み）　45-2111",},
    {name:"おしか清心苑",
    parking:true,
    babybed:false,
    multisheet:false,
    ostomate:true,
    button:true,
    showertoilet:true,
    popupContent:'<div class="popButton" onClick="modal_OshikaSeishin()"><p>おしか清心苑</p></div>',
    lat:38.299438,lon:141.500569,
    title: '<p><img src="icon/info.png" alt="おしか清心苑です。トイレに近い入り口は、不明です。専用駐車場があります。呼び出しボタンがあります。シャワートイレがあります">おしか清心苑<img onClick="back()"  src="icon/back.png" alt="このボタンで地図に戻ります"></p>',
    tdTime:"44-1654",},
    {name:"清優館①",
    parking:true,
    babybed:false,
    multisheet:false,
    ostomate:true,
    button:true,
    showertoilet:true,
    popupContent:'<div class="popButton" onClick="modal_OshikaSeiyu1()"><p>清優館①</p></div>',
    lat:38.298420,lon:141.499142,
    title: '<p><img src="icon/info.png" alt="清優館です。トイレに近い入り口は、不明です。専用駐車場があります。オストメイトあります。呼び出しボタンがあります。シャワートイレがあります">清優館①<img onClick="back()"  src="icon/back.png" alt="このボタンで地図に戻ります"></p>',
    tdTime:"８：３０〜１７：００　45-2611",},
    {name:"清優館②",
    parking:true,
    babybed:false,
    multisheet:false,
    ostomate:false,
    button:true,
    showertoilet:true,
    popupContent:'<div class="popButton" onClick="modal_OshikaSeiyu2()"><p>清優館②</p></div>',
    lat:38.297889,lon:141.498574,
    title: '<p><img src="icon/info.png" alt="清優館です。トイレに近い入り口は、不明です。専用駐車場があります。呼び出しボタンがあります。シャワートイレがあります">清優館②<img onClick="back()"  src="icon/back.png" alt="このボタンで地図に戻ります"></p>',
    tdTime:"８：３０〜１７：００　45-2611"},
    {name:"牡鹿交流センターほっとまる①",
    parking:true,
    babybed:false,
    multisheet:false,
    ostomate:false,
    button:true,
    showertoilet:true,
    popupContent:'<div class="popButton" onClick="modal_OshikaMaru1()"><p>牡鹿交流ｾﾝﾀｰほっとまる①</p></div>',
    lat:38.297536,lon:141.498337,
    title: '<p class="spMode"><img src="icon/info.png" alt="牡鹿交流センターほっとまるです。トイレに近い入り口は、不明です。専用駐車場があります。呼び出しボタンがあります。シャワートイレがあります">牡鹿交流センターほっとまる①<img onClick="back()"  src="icon/back.png" alt="このボタンで地図に戻ります"></p>',
    tdTime:"１３：００〜２０：００　45-3618",},
    {name:"牡鹿交流センターほっとまる②",
    parking:true,
    babybed:false,
    multisheet:false,
    ostomate:false,
    button:true,
    showertoilet:true,
    popupContent:'<div class="popButton" onClick="modal_OshikaMaru2()"><p>牡鹿交流ｾﾝﾀｰほっとまる②</p></div>',
    lat:38.296803,lon:141.498262,
    title: '<p class="spMode"><img src="icon/info.png" alt="牡鹿交流センターほっとまるです。トイレに近い入り口は、不明です。専用駐車場があります。呼び出しボタンがあります。シャワートイレがあります">牡鹿交流センターほっとまる②<img onClick="back()"  src="icon/back.png" alt="このボタンで地図に戻ります"></p>',
    tdTime:"１３：００〜２０：００　45-3618",},
    {name:"寄磯診療所",
    parking:true,
    babybed:false,
    multisheet:false,
    ostomate:true,
    button:true,
    showertoilet:true,
    popupContent:'<div class="popButton" onClick="modal_OshikaYoriiso()"><p>寄磯診療所</p></div>',
    lat:38.391484,lon:141.522424,
    title: '<p><img src="icon/info.png" alt="寄磯診療所です。トイレに近い入り口は、不明です。専用駐車場があります。オストメイトあります。呼び出しボタンがあります。シャワートイレがあります">寄磯診療所<img onClick="back()"  src="icon/back.png" alt="このボタンで地図に戻ります"></p>',
    tdTime:"９：００〜１６：００　48-2111",}, 
];
